/**
 * Migration runner — invoked via `pnpm db:migrate` (which is `tsx src/db/migrate.ts`).
 *
 * Uses drizzle-orm/neon-serverless/migrator (transactional, requires Pool).
 * Reads migrations from `./drizzle/migrations` (D-01 generate workflow — files
 * are pre-generated by `pnpm db:generate` and committed to git).
 *
 * Threat T-02-05 mitigation: redacts `user:pass@` segment from DATABASE_URL
 * before logging.
 */
import { Pool } from "@neondatabase/serverless";
import { drizzle } from "drizzle-orm/neon-serverless";
import { migrate } from "drizzle-orm/neon-serverless/migrator";

function redactUrl(url: string): string {
  return url.replace(/:\/\/[^@]+@/, "://***@");
}

async function main() {
  const url = process.env.DATABASE_URL;
  if (!url) throw new Error("DATABASE_URL is not set");

  const pool = new Pool({ connectionString: url });
  const db = drizzle(pool);

  console.log(
    JSON.stringify({ event: "migrate.start", url: redactUrl(url) }),
  );
  await migrate(db, { migrationsFolder: "./drizzle/migrations" });
  console.log(JSON.stringify({ event: "migrate.done" }));
  await pool.end();
}

main().catch((err) => {
  console.error(
    JSON.stringify({ event: "migrate.error", error: String(err) }),
  );
  process.exit(1);
});
