/**
 * ENSO Brasil — Pure risk engine type contracts (RISK-02, RISK-03, RISK-08).
 *
 * RiskLevel: state-level computed output (5 levels incl. unknown).
 * Severity: per-alert input dimension (4 values).
 * Alert: re-exported from sources/schema so calculate.ts can stay isolated
 *   (RISK-01 — depcruise rule allows calculate.ts to import only ./types).
 * SourcesHealthRow: minimal shape consumed by applyStaleness (decoupled from Drizzle).
 * StateSnapshotPayload: structural superset of P2 StateSnapshot (additive-only per RISK-08).
 *
 * Type-only module. Zero runtime exports. Excluded from coverage thresholds.
 */

import type { Severity, RiskLevel, Alert } from "@/lib/sources/schema";
import type { StateSnapshot } from "@/lib/api/schemas";

export type { Severity, RiskLevel };

/** Re-exported so calculate.ts honors the dependency-cruiser isolation rule (RISK-01). */
export type { Alert };

/**
 * Minimal shape for applyStaleness (RISK-07).
 * Decoupled from Drizzle row type to keep src/lib/risk/ free of @/db/* imports.
 * P4 will adapt the Drizzle inferred row to this shape at the wiring layer.
 */
export interface SourcesHealthRow {
  /** Source identifier (e.g., "cemaden", "inmet"). */
  source_key: string;
  /** ISO-8601 datetime string of last successful fetch, or null if never. */
  last_successful_fetch: string | null;
}

/**
 * Snapshot payload written by P4 wiring layer.
 *
 * Structural superset of P2 StateSnapshot (RISK-08 — additive only, no removed/renamed fields).
 * P3 ships the type; P4 imports it and writes to snapshot_cache.
 *
 * `explanation` is added in P3 to satisfy RISK-09 — UIs consume it as-is.
 */
export interface StateSnapshotPayload extends StateSnapshot {
  /** PT-BR plain-language explanation generated by `generateExplanation`. */
  explanation: string;
}
